### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by NekOware** [shaheer1642/relic-bot-ds#1]
https://github.com/shaheer1642/relic-bot-ds/blob/60673ac748f7978992bb8829ed9c2080bb8749b8/modules/trade_bot_modules.js#L8-L24
the features i was using myself were just removed from the lines referenced making me unable to use them and breaking my entire system.
If possible please add them back.

**Comment by shaheer1642** [comment]
idk upgrade your system to auto-delete references for when the the repo vulnerability is fixed. kekw
